// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/analysis_order/current": {
            "get": {
                "description": "Возвращает ID текущего чернового заказа и количество добавленных экспертов.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AnalysisOrders"
                ],
                "summary": "Получить информацию о текущем черновом заказе",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Resp_CurrTaskInfo"
                        }
                    },
                    "401": {
                        "description": "Требуется авторизация",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении данных",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/analysis_orders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список заявок. Пользователь видит только свои заявки, модератор — все заявки. Неавторизованный пользователь получает ошибку доступа.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AnalysisOrders"
                ],
                "summary": "Получить список заявок на анализ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фильтр по статусу",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Начальная дата (фильтр от)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Конечная дата (фильтр до)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список заявок",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.DTO_Resp_Order"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/analysis_orders/{id}": {
            "get": {
                "description": "Возвращает детальную информацию о заявке на анализ по её идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AnalysisOrders"
                ],
                "summary": "Получить заявку по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Детали заявки",
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Resp_Order"
                        }
                    },
                    "400": {
                        "description": "Invalid order ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Order not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет статус заявки и/или модератора, если это требуется",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AnalysisOrders"
                ],
                "summary": "Обновить заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Req_OrderUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновленная заявка",
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Resp_Order"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Полностью удаляет заказ анализа произведения искусства",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AnalysisOrders"
                ],
                "summary": "Удалить заказ на анализ",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заказа",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ID удалённого заказа",
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Resp_SimpleID"
                        }
                    },
                    "400": {
                        "description": "Invalid order ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/analysis_orders/{id}/form": {
            "put": {
                "description": "Переводит заявку из статуса черновика в статус сформированной",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AnalysisOrders"
                ],
                "summary": "Сформировать заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сформированная заявка",
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Resp_Order"
                        }
                    },
                    "400": {
                        "description": "Invalid order ID or cannot form order",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/analysis_orders/{id}/resolve": {
            "put": {
                "description": "Выполняет завершение или отклонение заявки по анализу произведения искусства. При завершении рассчитывается финальный композиционный центр.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AnalysisOrders"
                ],
                "summary": "Завершить/отклонить заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Действие с заявкой (action: complete | reject)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновлённая заявка",
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Resp_Order"
                        }
                    },
                    "400": {
                        "description": "Invalid input or missing required fields",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Order not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Добавляет JWT токен в черный список и выполняет деавторизацию",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Выход из системы",
                "responses": {
                    "200": {
                        "description": "Сообщение об успешном выходе\" {\"message\": \"Деавторизация прошла успешно\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid authorization header",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/draft/experts/{id}": {
            "post": {
                "description": "Добавляет указанного эксперта в текущий черновой заказ пользователя.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Experts"
                ],
                "summary": "Добавить эксперта в черновик заявки",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID эксперта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Resp_OrderExpertLink"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID эксперта",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Требуется авторизация",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при добавлении эксперта",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/experts": {
            "get": {
                "description": "Возвращает список всех экспертов. Поддерживает фильтрацию по названию.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Experts"
                ],
                "summary": "Получить список экспертов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фильтр по названию эксперта (подстрока)",
                        "name": "title",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.DTO_Resp_Expert"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт нового эксперта с указанными атрибутами.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Experts"
                ],
                "summary": "Создать нового эксперта",
                "parameters": [
                    {
                        "description": "Данные нового эксперта",
                        "name": "expert",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Req_ExpertCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.ArtExpert"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при создании эксперта",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/experts/{id}": {
            "get": {
                "description": "Возвращает полную информацию об эксперте по его идентификатору.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Experts"
                ],
                "summary": "Получить эксперта по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID эксперта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ArtExpert"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Эксперт не найден",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет параметры существующего эксперта.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Experts"
                ],
                "summary": "Обновить эксперта",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID эксперта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновлённые данные эксперта",
                        "name": "expert",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Req_ExpertCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ArtExpert"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные или ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при обновлении эксперта",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Полностью удаляет эксперта по ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Experts"
                ],
                "summary": "Удалить эксперта",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID эксперта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Resp_SimpleID"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при удалении эксперта",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/experts/{id}/image": {
            "post": {
                "description": "Загружает изображение и сохраняет URL в базе данных.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Experts"
                ],
                "summary": "Загрузить изображение эксперта",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID эксперта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Изображение эксперта",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Resp_UploadImg"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID или отсутствует файл",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при загрузке изображения",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/orders/{order_id}/experts/{expert_id}": {
            "put": {
                "description": "Обновляет координаты центра, переданные экспертом, в рамках заказа анализа",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "M-M"
                ],
                "summary": "Обновить параметры эксперта",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заказа",
                        "name": "order_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID эксперта",
                        "name": "expert_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новые координаты эксперта",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.updateExpertRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновлённые данные эксперта",
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Resp_UpdateExpert"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет связь между экспертом и заказом анализа",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "M-M"
                ],
                "summary": "Удалить эксперта из заказа",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заказа",
                        "name": "order_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID эксперта",
                        "name": "expert_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация об удалённой связи",
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Resp_OrderExpertLink"
                        }
                    },
                    "400": {
                        "description": "Invalid IDs",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает данные аутентифицированного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Получить текущего пользователя",
                "responses": {
                    "200": {
                        "description": "Данные пользователя",
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Resp_User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет пароль текущего аутентифицированного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Обновить данные пользователя",
                "parameters": [
                    {
                        "description": "Новые данные пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Req_UserUpd"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновленные данные пользователя",
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Resp_User"
                        }
                    },
                    "400": {
                        "description": "Invalid input data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Выполняет вход пользователя и возвращает JWT токен",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Аутентификация пользователя",
                "parameters": [
                    {
                        "description": "Учетные данные",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Req_UserReg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Токен и данные пользователя",
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Resp_TokenLogin"
                        }
                    },
                    "400": {
                        "description": "Invalid input data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Создает нового пользователя с указанными логином и паролем",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Req_UserReg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Зарегистрированный пользователь",
                        "schema": {
                            "$ref": "#/definitions/handler.DTO_Resp_User"
                        }
                    },
                    "400": {
                        "description": "Invalid input data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.DTO_Req_ExpertCreate": {
            "description": "Данные для добавления нового эксперта",
            "type": "object",
            "required": [
                "algorithm",
                "name",
                "title"
            ],
            "properties": {
                "algorithm": {
                    "type": "string",
                    "example": "luminosity_center"
                },
                "description": {
                    "type": "string",
                    "example": "Использует метод яркостного центра"
                },
                "img_url": {
                    "type": "string",
                    "example": "expert_photo.png"
                },
                "name": {
                    "type": "string",
                    "example": "Иванов И.И."
                },
                "status": {
                    "type": "boolean",
                    "example": true
                },
                "title": {
                    "type": "string",
                    "example": "Центр композиционного анализа №1"
                }
            }
        },
        "handler.DTO_Req_OrderUpdate": {
            "type": "object",
            "properties": {
                "moderator_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handler.DTO_Req_UserReg": {
            "description": "Данные для регистрации нового пользователя",
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "example": "art_user"
                },
                "password": {
                    "type": "string",
                    "example": "secure_password_123"
                }
            }
        },
        "handler.DTO_Req_UserUpd": {
            "description": "Данные для обновления пароля пользователя",
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "new_secure_password"
                }
            }
        },
        "handler.DTO_Resp_CurrTaskInfo": {
            "description": "Статистика по текущей задаче пользователя",
            "type": "object",
            "properties": {
                "experts_count": {
                    "type": "integer",
                    "example": 3
                },
                "order_id": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "handler.DTO_Resp_Expert": {
            "description": "Полная информация об эксперте",
            "type": "object",
            "properties": {
                "algorithm": {
                    "type": "string",
                    "example": "geometric_center"
                },
                "description": {
                    "type": "string",
                    "example": "Определяет композиционный центр"
                },
                "id_artcenter": {
                    "type": "integer",
                    "example": 1
                },
                "img_url": {
                    "type": "string",
                    "example": "expert_photo.png"
                },
                "name": {
                    "type": "string",
                    "example": "Иванов И.И."
                },
                "status": {
                    "type": "boolean",
                    "example": true
                },
                "title": {
                    "type": "string",
                    "example": "Центр анализа №1"
                }
            }
        },
        "handler.DTO_Resp_Order": {
            "description": "Полная информация о заявке с экспертами",
            "type": "object",
            "properties": {
                "date_completed": {
                    "type": "string",
                    "example": "2025-11-07T12:00:00Z"
                },
                "date_created": {
                    "type": "string",
                    "example": "2025-11-05T12:00:00Z"
                },
                "date_formed": {
                    "type": "string",
                    "example": "2025-11-06T12:00:00Z"
                },
                "experts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.DTO_Resp_OrderExpert"
                    }
                },
                "id_creator": {
                    "type": "integer",
                    "example": 1
                },
                "id_moderator": {
                    "type": "integer",
                    "example": 2
                },
                "id_order": {
                    "type": "integer",
                    "example": 5
                },
                "order_status": {
                    "type": "string",
                    "enum": [
                        "draft",
                        "formed",
                        "completed",
                        "rejected"
                    ],
                    "example": "formed"
                },
                "result_x": {
                    "type": "number",
                    "example": 0.51
                },
                "result_y": {
                    "type": "number",
                    "example": 0.48
                }
            }
        },
        "handler.DTO_Resp_OrderExpert": {
            "description": "Информация об эксперте внутри заявки",
            "type": "object",
            "properties": {
                "algorithm": {
                    "type": "string",
                    "example": "force_lines"
                },
                "center_x": {
                    "type": "number",
                    "example": 123.45
                },
                "center_y": {
                    "type": "number",
                    "example": 234.56
                },
                "id_artcenter": {
                    "type": "integer",
                    "example": 3
                },
                "id_order": {
                    "type": "integer",
                    "example": 5
                },
                "name": {
                    "type": "string",
                    "example": "Сидоров П.П."
                },
                "title": {
                    "type": "string",
                    "example": "Центр композиционного анализа №3"
                }
            }
        },
        "handler.DTO_Resp_OrderExpertLink": {
            "description": "Информация о связи между задачей и гейтом",
            "type": "object",
            "properties": {
                "id_artcenter": {
                    "type": "integer",
                    "example": 3
                },
                "id_order": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handler.DTO_Resp_SimpleID": {
            "description": "Ответ, содержащий только идентификатор",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handler.DTO_Resp_TokenLogin": {
            "description": "JWT токен и данные пользователя",
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user": {
                    "$ref": "#/definitions/handler.DTO_User"
                }
            }
        },
        "handler.DTO_Resp_UpdateExpert": {
            "description": "Результат обновления углов поворота гейта",
            "type": "object",
            "properties": {
                "center_x": {
                    "type": "number",
                    "example": 45.5
                },
                "center_y": {
                    "type": "number",
                    "example": 45.5
                },
                "expert_id": {
                    "type": "integer",
                    "example": 2
                },
                "order_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handler.DTO_Resp_UploadImg": {
            "description": "Результат загрузки изображения эксперта",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "image": {
                    "type": "string",
                    "example": "expert_image.png"
                }
            }
        },
        "handler.DTO_Resp_User": {
            "description": "Упрощенные данные пользователя",
            "type": "object",
            "properties": {
                "login": {
                    "type": "string",
                    "example": "art_researcher"
                }
            }
        },
        "handler.DTO_User": {
            "description": "Информация о пользователе системы",
            "type": "object",
            "properties": {
                "id_user": {
                    "type": "integer",
                    "example": 1
                },
                "is_admin": {
                    "type": "boolean",
                    "example": false
                },
                "login": {
                    "type": "string",
                    "example": "art_researcher"
                }
            }
        },
        "handler.updateExpertRequest": {
            "type": "object",
            "properties": {
                "center_x": {
                    "type": "number"
                },
                "center_y": {
                    "type": "number"
                }
            }
        },
        "model.AnalysisOrder": {
            "type": "object",
            "properties": {
                "dateCompleted": {
                    "type": "string"
                },
                "dateCreated": {
                    "type": "string"
                },
                "dateFormed": {
                    "type": "string"
                },
                "expertsLinks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ExpertsToOrders"
                    }
                },
                "id_creator": {
                    "type": "integer"
                },
                "id_moderator": {
                    "type": "integer"
                },
                "id_order": {
                    "type": "integer"
                },
                "moderator": {
                    "$ref": "#/definitions/model.Users"
                },
                "orderStatus": {
                    "type": "string"
                },
                "resultX": {
                    "type": "number"
                },
                "resultY": {
                    "type": "number"
                },
                "user": {
                    "$ref": "#/definitions/model.Users"
                }
            }
        },
        "model.ArtExpert": {
            "type": "object",
            "properties": {
                "algorithm": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id_artcenter": {
                    "type": "integer"
                },
                "imgURL": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "orders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ExpertsToOrders"
                    }
                },
                "status": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.ExpertsToOrders": {
            "type": "object",
            "properties": {
                "analysisOrder": {
                    "$ref": "#/definitions/model.AnalysisOrder"
                },
                "artExpert": {
                    "$ref": "#/definitions/model.ArtExpert"
                },
                "centerX": {
                    "type": "number",
                    "format": "float32"
                },
                "centerY": {
                    "type": "number",
                    "format": "float32"
                },
                "id_artcenter": {
                    "type": "integer"
                },
                "id_order": {
                    "type": "integer"
                }
            }
        },
        "model.Users": {
            "type": "object",
            "properties": {
                "id_user": {
                    "type": "integer"
                },
                "isModerator": {
                    "type": "boolean"
                },
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT токен в формате: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Art Analysis API",
	Description:      "API для анализа композиционного центра произведений искусства",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
